### ISSUE TITLE
View Inventory Count for a Specific Product

### ISSUE THREAD

**Issue by jdunle01** [devops-inventory/inventory#1]
**As a...** Inventory Manager
**I want to...** See how many units of a specific product are in stock
**So that...** I know if I need to make another order

**Assumptions**
Inventory Managers will be able to see all products in the catalog, there are no security restrictions

**Acceptance Criteria**
Given that I navigate to a specific product (via the catalog or search), then I expect that on the product page I will see a count of the number of Inventory in stock at that time

Given that a product has an inventory count of 0, then I expect to see some indication that the product is "Out of Stock"

**Comment by samanthambrown** [comment]
Milestone 1 - basic requirement for general functionality

**Comment by ni482** [comment]
Believe we should be also good with this as well?
