### ISSUE TITLE
Know When Inventory is Out of Stock

### ISSUE THREAD

**Issue by jdunle01** [devops-inventory/inventory#10]
**As a...** Inventory Manager
**I want to...** know if a specific inventory is out of stock
**So that...** I know if I need to re-order that particular inventory

**Assumptions**

**Acceptance Criteria**
Given that there are inventory items with a count = 0 or < 1, then I expect that when I search for inventory by count = 0, then I will return these results
As an inventory manager, I will be inclined to re-reorder this inventory 
I do not expect that an alert will be shown when inventory falls to 0 as this particular point in time. Good candidate for a future story

**Comment by jdunle01** [comment]
I have updated the acceptance criteria of this user story. A user story for an actual alert when Inventory falls to 0 is a good candidate for a future Sprint

**Comment by samanthambrown** [comment]
Covered in a different story, can move to closed.

**Comment by jdunle01** [comment]
assigned to R.S.
