### ISSUE TITLE
Real Time Inventory Update

### ISSUE THREAD

**Issue by jdunle01** [devops-inventory/inventory#2]
**As a...** Inventory Manager
**I want to...** See the count of inventory change following an order
**So that...** the system is up to date and no products can get ordered when they are out of stock

**Assumptions**

Inventory Managers will be able to see all products in the catalog, there are no security restrictions

**Acceptance Criteria**
Given that a product is ordered, then I expect the inventory count for that product to be updated within 10 minutes of the order

**Comment by samanthambrown** [comment]
working on this one together, assigned jeff as the lead

**Comment by jdunle01** [comment]
I think we will need to pull in some other teams, right? Like orders and shopping cart?
