### ISSUE TITLE
Build Database Model for Inventory

### ISSUE THREAD

**Issue by jdunle01** [devops-inventory/inventory#21]
Added the following attributes to our model

name(string) - the name of the product
category (string) - the category the product belongs to (i.e., food, apparel, accessories, games, kitchenware)
available (boolean) - True for products that are currently in stock
condition (string) - The quality of the product's state (i.e. new, used, poor)
count (int) - The quantity in stock

**Comment by samanthambrown** [comment]
closing this issue because I already see all of the attributes that you are discussing above, we pushed earlier today.
