### ISSUE TITLE
Do Not Allow an Order of Inventory if it is Out of Stock

### ISSUE THREAD

**Issue by jdunle01** [devops-inventory/inventory#3]
**As a...** Customer
**I want to...** not be able to order a product if it is out of stock
**So that...** I only pay for products that I will actually receive

**Assumptions**
Customers should still be able to _see_ a product on the site if it is out of stock 

**Acceptance Criteria**
Given that a product has an inventory count of 0, then I expect that when I attempt to purchase that product on the e commerce site that I will receive a message or indication that this product is not available to be ordered at this time

Given that an Inventory Item falls from a stock of 1 to a stock of 0, then I expect that the inventory item will move to a status of Out of Stock (user story #10), and I expect that this will publish to the other teams such as Shopping Cart so that the item cannot be used.

**Comment by samanthambrown** [comment]
Dependent on working with the "order" -- might be harder to do technically. Sprint 2

**Comment by jdunle01** [comment]
**Comment from Rofrano about what a stateful service is**

Yes, remember when I gave Cancelling an Order as an example:
```/orders/123/cancel```
Would be a stateful action on an Order that not only changes the state to `cancelled` but also probably notifies shipping and receiving or the warehouse or payments, etc. You do not have to notify anyone in your project code but you get the idea that an action can be taken on an order like that.
