### ISSUE TITLE
Track Item Condition

### ISSUE THREAD

**Issue by samanthambrown** [devops-inventory/inventory#4]
**As a...** Customer
**I want to...** be able to track the condition of an item
**So that...** I can query products by their condition (brand new, used, slightly used, poor)

**Assumptions**
Customers should know the condition of the item before purchasing

**Acceptance Criteria**
When a product is available for purchase, the condition of the product must be indicated clearly on the product page.

**Comment by ni482** [comment]
Believe this should be closed?
