### ISSUE TITLE
Implement a RESTful Action URL

### ISSUE THREAD

**Issue by samanthambrown** [devops-inventory/inventory#55]
**As a** inventory manager
**I want to** access the inventory module using a RESTful Action URL
**So that** I can make an action-based call on inventory items while performing my job

**Assumptions** RESTful URL implementation is assumed to be best practice.

**Acceptance Criteria**
If you want to disable a resource like a user group:
• If the resource had a representation of it’s status you could use a PUT request to change that
status
• RESTful Example: Disable UserGroup with id 123
PUT http://api.myapp.com/user-group/123
{
 ...
 status: "disabled"
}

**Comment by ni482** [comment]
In case anyone has a chance to look at this, can close

**Comment by jdunle01** [comment]
Just looked at this issue, looks good. Thus, moving to closed!
