### ISSUE TITLE
Add Persistence to Application and Model

### ISSUE THREAD

**Issue by samanthambrown** [devops-inventory/inventory#57]
**As a** inventory manager
**I want to** use an application that uses persistent storage
**So that** the inventory module can survive service restarts and we can reduce the risk of a customer being able to order a product that is out of stock

**Assumptions** Manually deploying our application is not scalable and persistence is needed for our model to survive restarts.

**Acceptance Criteria**
1. Add persistent storage using Cloudant or CouchDB. 
2. Modify models.py file to add persistence to our model definition of your resource. 
3. Modify application to get the database credentials from the VCAP_SERVICES environment variable.
4. Add persistence to your Vagrantfile as a Docker container.

**Comment by samanthambrown** [comment]
Helpful tips from Rofrano: SQLAlchemy is a good framework for working with relational databases and is recommended if you are going to use SQL. The GitHub repo http://github.com/nyu-devops/lab-flask-sqlalchemy has sample code for SQL and http://github.com/nyu-devops/lab-bluemix-cf has sample code for CouchDB/Cloudant you can use as a guide.

**Comment by samanthambrown** [comment]
For modifying the application to get the database credentials, see models.py in lab-bluemix-cf for an example.

**Comment by samanthambrown** [comment]
Got Cloudant + Service Credentials through IBM Cloud

**Comment by ni482** [comment]
Is this still in progress?

**Comment by samanthambrown** [comment]
Yes @ni482 ! I'm only on the 2nd step (might need help with this during the sprint time tomorrow.)

**Comment by ni482** [comment]
New pull request has been requested related to this issue
