### ISSUE TITLE
Create and Name Cloud Foundry application in IBM Cloud

### ISSUE THREAD

**Issue by samanthambrown** [devops-inventory/inventory#58]
**As a** inventory manager
**I want to** know the name of my Cloud Foundry application in the IBM Cloud
**So that** I can access the proper URL to do the necessary inventory related work for my job

**Assumptions** Naming the application becomes your URL, and the base for deploying our application to the cloud

**Acceptance Criteria**
1. Cloud Foundry application is created in IBM Cloud
2. IBM Cloud microservice is named nyu-inventory-service-s19

**Comment by samanthambrown** [comment]
The full URL will then be nyu-inventory-service-s19.mybluemix.net

**Comment by ni482** [comment]
Attempting this now

**Comment by ni482** [comment]
<img width="854" alt="Screen Shot 2019-04-08 at 6 10 40 PM" src="https://user-images.githubusercontent.com/46497143/55760318-b77b9780-5a29-11e9-9553-7b41afb58b0a.png">
