### ISSUE TITLE
Create and Bind Database service for Cloud Foundry app

### ISSUE THREAD

**Issue by samanthambrown** [devops-inventory/inventory#59]
**As a** inventory manager
**I want to** have all inventory records in a Cloud Foundry database
**So that** the inventory records are stored securely and consistently across the application, and so that the inventory microservice shares the same back end database as the other services (orders, customers, etc.) to ensure data consistency

**Assumptions** Cloud Foundry application is already created and named

**Acceptance Criteria**
1. Database service is created for Cloud Foundry app
2. Database service is bound to the Cloud Foundry app

**Comment by ni482** [comment]
Created and bound... 
<img width="690" alt="Screen Shot 2019-04-11 at 3 16 50 PM" src="https://user-images.githubusercontent.com/46497143/55985033-dddd4500-5c6c-11e9-9566-64e29a7aa58e.png">

**Comment by ni482** [comment]
<img width="1403" alt="Screen Shot 2019-04-13 at 5 35 15 PM" src="https://user-images.githubusercontent.com/46497143/56085515-8b3d8d80-5e12-11e9-8f54-bf3a61b9105a.png">
