### ISSUE TITLE
Add New Inventory

### ISSUE THREAD

**Issue by samanthambrown** [devops-inventory/inventory#6]
**As a...** inventory manager
**I want to...** add new inventory 
**So that...** new products can be quickly and easily added to the platform to proactively stay ahead of customer demand and industry trends

**Assumptions**
-Inventory can be added any day of the week and any time of day
-Customer demand and industry trends are not static
-Inventory managers are aware of the current inventory, in order to prevent duplicate inventory

**Acceptance Criteria**
-When a new inventory item is added, specific criteria will be required, including: quantity, name of item, description, and quality.

**Comment by ni482** [comment]
Agreed this should be milestone 1, since other stories are dependent on this action.

**Comment by samanthambrown** [comment]
QA'ed and test cases written
