### ISSUE TITLE
Push Application to IBM Cloud

### ISSUE THREAD

**Issue by samanthambrown** [devops-inventory/inventory#60]
**As a** inventory manager
**I want to** use the Inventory application in the IBM Cloud
**So that** I can access the system any time, anywhere, and know that the service is running on IBM Cloud with persistence

**Assumptions** We need to download and install the IBM Cloud CLI in our vagrant VM, and create the necessary Cloud Foundry metadata files, in order to deploy our application to IBM Cloud.

**Acceptance Criteria**
1. Download and install the IBM Cloud CLI in your vagrant VM (added to the Vagrantfile as per the nyu-devops/lab-bluemix-cf repo).
2. Create the necessary Cloud Foundry metadata files for deployment (manifest.yml, Procfile, runtime.txt) file so that IBM Cloud will know how to deploy your application (hint: see lab-bluemix-cf).
3. Use cf push to push your application to IBM Cloud (Bluemix)
4. Go to the URL of your service and make sure that it works

**Comment by ni482** [comment]
just a reminder that we need to switch to using 2 instances **before** submitting!

**Comment by ni482** [comment]
attempting to push this now, fingers crossed

**Comment by ni482** [comment]
Current status = 1/2 running, 404 error on URL
<img width="752" alt="Screen Shot 2019-04-14 at 9 22 08 PM" src="https://user-images.githubusercontent.com/46497143/56103121-18f6a700-5eff-11e9-889b-b84081f2ad9b.png">
<img width="1298" alt="Screen Shot 2019-04-14 at 9 22 00 PM" src="https://user-images.githubusercontent.com/46497143/56103122-18f6a700-5eff-11e9-9ccc-fba624e094fe.png">

**Comment by samanthambrown** [comment]
Debugging, when we looked at the logs, it says "2019-04-15T18:36:46.25+0000 [API/14] OUT Created app with guid d243f03f-1a77-4aef-84d2-72b8fb5dd51e"
