### ISSUE TITLE
Delete inventory

### ISSUE THREAD

**Issue by ni482** [devops-inventory/inventory#8]
**As a...** inventory manager
**I want to...** delete inventory
**So that...** products can be quickly and easily removed from the platform in response of changes in customer demand, industry trends, and supplier availability

**Assumptions**
-Inventory can be deleted any day of the week and any time of the day
-Customer demand, industry trends, and supplier availability are not static

**Acceptance Criteria**
-When inventory item is deleted, warning notification of "Are you sure you want to delete this item" along with specific criteria including quantity, name of item, description, and quality will pop-up before having to confirm "OK" or "Cancel".

**Comment by samanthambrown** [comment]
QAed and test case passed
