### ISSUE TITLE
Add "List" Scenario to files and BDD Test

### ISSUE THREAD

**Issue by samanthambrown** [devops-inventory/inventory#81]
**As a** inventory manager
**I want to** make sure that inventory can be listed in the UI
**So that** I know the "List" function is running correctly before deploying to prod

**Assumptions**
-The feature file is written using the Gherkin syntax understood by the behave tool
-The .feature and .steps files are created

**Acceptance Criteria**:
**Given** the app is running
**When** I run behave with "List" written into the feature and steps file
**Then** the BDD test passes and the "List" scenario is green

**Comment by ni482** [comment]
As per latest code push this is done. Moving to closed
