### ISSUE TITLE
Create a UI to test with behave using Selenium

### ISSUE THREAD

**Issue by samanthambrown** [devops-inventory/inventory#83]
**As a** inventory manager
**I want to** create a UI to test with behave
**So that** I can easily test functionality before it breaks on customers

**Assumptions**
-Selenium tests the integration of multiple microservices that share a common user interface

**Acceptance Criteria**:

**Given** we need to add 7 BDD tests 
**And** Selenium automates browsers
**When** someone goes to the app's UI
**Then** they should be able to test inventory actions with behave

**Comment by samanthambrown** [comment]
Copying the static folder and files from lab-flask-BDD

**Comment by ni482** [comment]
Working through some of the html / js
