### ISSUE TITLE
View All Inventory

### ISSUE THREAD

**Issue by jdunle01** [devops-inventory/inventory#9]
**As a...** inventory manager
**I want to...** view all inventory on a single page
**So that...** I can quickly get an idea of all items

**Assumptions**
Inventory managers can view all inventory

**Acceptance Criteria**
Given that select View All Inventory, I expect that I will see two columns one with Inventory name and another with Inventory count

**Comment by ni482** [comment]
Closing this issue after it has been merged into master!

**Comment by ni482** [comment]
Still need to run test on
